### ISSUE TITLE
(Minor Issue) Fix colours of text in buttons

### ISSUE THREAD

**Issue by mesosoi** [Silverware-Games/matchy-star-issues#1]
The button is green, but the text colour there is red. The text colour should be white instead.

[Image](https://s1.hostingkartinok.com/uploads/images/2022/09/73af3bf1ca9ddea5817f3a860f0a46ab.png)

**Comment by michaelplzno** [comment]
For which button? I'll poke around to see if I can find it.

**Comment by mesosoi** [comment]
> For which button? I'll poke around to see if I can find it.

The green button, lol https://s1.hostingkartinok.com/uploads/images/2022/09/73af3bf1ca9ddea5817f3a860f0a46ab.png

**Comment by michaelplzno** [comment]
Oh lmao, I can fix that. Maybe make it a light green text.
