### ISSUE TITLE
Can't launch the game in 1920x1080 Windowed mode, but can resize the game after launching

### ISSUE THREAD

**Issue by mesosoi** [Silverware-Games/matchy-star-issues#4]
Can't launch the game in 1920x1080 Windowed mode, but can resize the game after launching just fine. The launcher app should allow players to select 1920x1080 (as well as many other famous screen resolutions) in Windowed mode.

**Comment by michaelplzno** [comment]
I'm going to try to update the game to the latest version of unity which will remove the launcher.
